model:
  d_inp: 1024
  d_model: 128
data:
  num_workers: 2
  name: summe
  setting: Canonical 
  split: 0
  num_frames: 200
  paths:
    interim: 'data/interim/'
    youtube8M: 'data/interim/youtube8M/selected_features'

hparams:
  lr: 0.0001
  weight_decay: 0.0001
  ratio_s:  0.2
  ratio_k1: 0.1
  alpha: 0.5
  num_frames: 200
  batch_size: 32
  n_layer: 4
  n_head: 1
  rince_q: 0.3
  rince_lam: 0.5
  our_lam: 0.5
setup:
  is_logger: False
  wandb_name: video-sum

lightning:
  trainer:
    max_epochs: 40
    log_every_n_steps: 100

is_raw: False
use_unq: True 
use_unif: True
use_neg: True
use_rince: True
use_ours: False